pipeline {
	agent {
		docker {
			image 'maven:3'	
			args '-v /root/.m2:/root/.m2'
		}
	}
	stages {
		stage('Build') {
			steps {
				sh 'mvn -B -DskipTests clean package'
			}
		}
		stage('Create docker image') {
			steps {
				dir('docker')
				sh 'docker build .'
			}	 
		}
	}
}
