pipeline {
	agent none
	stages {
		stage('Build') {
			agent {
				docker {
					image 'maven:3'	
					args '-v $HOME/.m2:/root/.m2'
				}
			}
			steps {
				sh 'mvn -B -DskipTests clean package'
			}
		}
		stage('Create docker image') {
			agent any
			steps {
				sh 'docker build .'
			}	 
		}
	}
}
