pipeline {
	agent none
	stages {
		stage('Build') {
			agent {	label 'maven' }
			steps {
				sh 'mvn -B -DskipTests clean package'	
				script {			
					stash name: 'target', includes: 'target/calc-1.0-SNAPSHOT.jar'
				}
			}
		}
		stage('Create docker image') {
			agent { label 'docker'}
			steps {
				script {
					unstash 'target'
				}
				sh 'docker build .'
			}	 
		}
	}
}
